# Generated by Django 4.2.28 on 2026-02-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amazon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="name", field=models.CharField(max_length=100),
        ),
    ]
